#!/bin/bash

exec >>/home/ubuntu/lolschedule.log 2>&1
set -e
set -x

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOME="/home/ubuntu"

. ~/environment
cd ~/lolschedule
rake